# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0c\x66ile_service\"*\n\x10\x44irectoryRequest\x12\x16\n\x0e\x64irectory_path\x18\x01 \x01(\t\" \n\x0b\x46ileRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x19\n\x08\x46ileList\x12\r\n\x05\x66iles\x18\x01 \x03(\t\"\x1e\n\x0b\x46ileContent\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\x93\x01\n\x0b\x46ileService\x12\x43\n\tListFiles\x12\x1e.file_service.DirectoryRequest\x1a\x16.file_service.FileList\x12?\n\x07GetFile\x12\x19.file_service.FileRequest\x1a\x19.file_service.FileContentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIRECTORYREQUEST']._serialized_start=36
  _globals['_DIRECTORYREQUEST']._serialized_end=78
  _globals['_FILEREQUEST']._serialized_start=80
  _globals['_FILEREQUEST']._serialized_end=112
  _globals['_FILELIST']._serialized_start=114
  _globals['_FILELIST']._serialized_end=139
  _globals['_FILECONTENT']._serialized_start=141
  _globals['_FILECONTENT']._serialized_end=171
  _globals['_FILESERVICE']._serialized_start=174
  _globals['_FILESERVICE']._serialized_end=321
# @@protoc_insertion_point(module_scope)
